### PR TITLE
OSM API + OpenDRI integrations changes

### PR DESCRIPTION
**Pull request by tiagojsag**
- Project setup
Added an eslint configuration. This configuration is intended to give the fewest errors possible with the existing codebase. We complied to it only on the code we added and haven't fixed errors on the existing code to avoid a too difficult merge to the upstream. (note: uses babel-eslint to support ES7 features)
- Added support for a trimmed down UI for embedded rendering
This adds a more compact interface to the compare view. It is not yet exposed to the user but can be used by appending `/embed` to the app URL (for instance `#/compare/bbox:-193.71094,-45.07477,264.02344,56.27190/2011...now/buildings/embed/`)
- Added basic theming support for a more seamless integration with 3rd party sites (OpenDRI theme included)
This adds the possibility yo customize some UI elements to match a 3rd party hosting site. It is not yet exposed to the user but can be used by appending `/embed/[themeName]` to the app URL (for instance `/#/compare/bbox:-193.71094,-45.07477,264.02344,56.27190/2011...now/buildings/embed/opendri`)
- Fix issue preventing river data from rendering correctly
- Fix issue preventing KM statistics from rendering correctly
- Update settings to new endpoints
- Reviewed tileset configurations to match the new cruncher logic (see https://github.com/hotosm/osm-analytics-cruncher/issues/15)

### CODE REVIEW

**Comment by nerik** [comment]
Fixes https://github.com/hotosm/osm-analytics/issues/63

**Comment by tyrasd** [comment]
These changes look all good to me! :+1: Only a few minor comments from my side:

1. Personally, I would have liked the `embed` parameter/setting to be placed somewhere else (not at the end of the page-routing parameters, because it behaves a bit different from the other parameter there –
e.g. it doesn't update the content of the site without hitting reload). It could have been an optional get parameter on the index.html, or something similar. But I guess that's more like a matter of taste.
2. Since the waterways layer doesn't have been processed with the historic osm-qa-tiles extracts, it should be added to the exclusions here: https://github.com/GFDRR/osm-analytics/blob/05e1e5f2fca0638cff92fe01e5f8d503261ec54c/app/settings/options.js#L36-L48 (or even better: process the data for it).
3. And – I know it really doesn't belong to this PR, but I couldn't help noticing – it would be nice to tweak the waterways layer [style](
https://github.com/hotosm/osm-analytics/pull/74/files#diff-8bc3dfd0296060c783823fe61ba9a957) a bit, because it currently looks very faint in most regions (like [here](https://osm-analytics-ui.vizzuality.com/#/show/bbox:10.66862,46.39979,11.48669,46.80136/waterways/recency)).

**Comment by cgiovando** [comment]
@nerik can you please follow up on @tyrasd's comments above? Not sure if those are blockers, but we would need the changes merged ASAP - thanks!

CC: @david-hotosm

**Comment by nerik** [comment]
@tyrasd Thanks for reviewing this and sorry for the delay responding. I added a couple of edits.
1. I see your point, but we felt unnecessary to have the embed param acting live, since the result of it is typically at page load. Changing it now would have side effects on the wp-osma-charts used on the OpenDRI website, so I'm keeping this as it is for now
2. Done. 
3. Also done, it does indeed looks better:
screen shot 2017-09-28 at 17 54 57

**Pull request merged**
